#!/bin/bash
cd "$(dirname "$0")"
# if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
#  git pull
# fi

# printf '\e[3;0;0t'
# printf '\e[8;720;1280t'
# printf '\e[9;1t'
# printf '\e[5t'
# clear


node main.js
